# Generated by Django 4.2.5 on 2024-04-24 23:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('slug', models.SlugField(default=uuid.uuid1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archive', models.BooleanField(default=False)),
                ('password_reset_count', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True)),
                ('user_type', models.CharField(choices=[('ADMIN', 'ADMIN'), ('PARENT', 'PARENT'), ('CHILD', 'CHILD'), ('TUTEUR', 'TUTEUR')], default='PARENT', max_length=50)),
                ('accepted_terms', models.BooleanField(default=False, verbose_name="Accepté les conditions d'utilisation")),
                ('registration_method', models.CharField(choices=[('GOOGLE', 'GOOGLE'), ('FACEBOOK', 'FACEBOOK'), ('APPLE', 'APPLE'), ('NORMAL', 'NORMAL')], default='normal', max_length=50)),
                ('otp_token', models.CharField(blank=True, max_length=6, null=True, verbose_name='Token OTP')),
                ('gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='Genre')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
