# Generated by Django 4.2.5 on 2024-05-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountid', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=11)),
                ('ret_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ret_url', models.URLField(blank=True, null=True)),
                ('start_date', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.CharField(blank=True, max_length=255, null=True)),
                ('stop_time', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField()),
                ('to', models.CharField(max_length=255)),
            ],
        ),
    ]
