# Generated by Django 4.2.5 on 2024-05-03 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_telephone', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('api.user',),
        ),
        migrations.RemoveField(
            model_name='otp',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_reset_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_de_naissance', models.DateField()),
                ('type_appareil', models.CharField(max_length=100)),
                ('numeros_urgences', models.TextField()),
                ('ecole', models.CharField(blank=True, max_length=100, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('api.user',),
        ),
    ]
