# Generated by Django 4.2.5 on 2024-05-03 00:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_parent_remove_otp_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='slug',
            field=models.SlugField(default=uuid.uuid1),
        ),
        migrations.AddField(
            model_name='sms',
            name='slug',
            field=models.SlugField(default=uuid.uuid1),
        ),
    ]
