# Generated by Django 4.2.5 on 2024-05-05 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pendinguser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.AddField(
            model_name='otp',
            name='pending_user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.pendinguser'),
        ),
    ]
