# Generated by Django 5.0.4 on 2024-05-07 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_pendinguser_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendinguser',
            old_name='email',
            new_name='email_pending',
        ),
    ]
