# Generated by Django 5.0.4 on 2024-05-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_email_pending_pendinguser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
