# Generated by Django 5.0.4 on 2024-05-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_pendinguser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
    ]
