# Generated by Django 5.0.4 on 2024-05-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_parentchildlink_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentchildlink',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
