# Generated by Django 5.0.4 on 2024-05-07 22:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_parentchildlink_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentchildlink',
            name='slug',
            field=models.SlugField(default=uuid.uuid1),
        ),
    ]
