# Generated by Django 5.0.4 on 2024-05-10 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_parentchildlink_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='pending_user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pendinguser'),
        ),
    ]
