# Generated by Django 5.0.4 on 2024-05-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_parentchildlink_parent_familymember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('papa', 'Papa'), ('maman', 'Maman'), ('tante', 'Tante'), ('oncle', 'Oncle'), ('grand-mere', 'Grand-mère'), ('grand-pere', 'Grand-père')], max_length=100),
        ),
    ]
