# Generated by Django 5.0.4 on 2024-05-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='telephone',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
