# Generated by Django 5.0.4 on 2024-05-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_parent_telephone_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='ecole',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='numeros_urgences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='type_appareil',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
