# Generated by Django 5.0.4 on 2024-05-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
