# Generated by Django 5.0.4 on 2024-05-22 18:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_pendinguser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('adresse', models.CharField(max_length=255)),
                ('datetime_localisation', models.DateTimeField(default=django.utils.timezone.now)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.child')),
            ],
        ),
    ]
