# Generated by Django 5.0.4 on 2024-06-04 10:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_pendinguser_email_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergy',
            name='slug',
            field=models.SlugField(default=uuid.uuid1),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='slug',
            field=models.SlugField(default=uuid.uuid1),
        ),
        migrations.AddField(
            model_name='emergencynumber',
            name='slug',
            field=models.SlugField(default=uuid.uuid1),
        ),
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.SlugField(default=uuid.uuid1),
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid1)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('relationship', models.CharField(choices=[('papa', 'Papa'), ('maman', 'Maman'), ('tuteur', 'Tuteur'), ('autre', 'Autre')], max_length=20)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='api.parent')),
            ],
        ),
    ]
