# Generated by Django 5.0.4 on 2024-06-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_emergencyalert_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyalert',
            name='state',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('traite', 'Traité')], default='en_attente', max_length=20),
        ),
    ]
