# Generated by Django 5.0.4 on 2024-07-31 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_emergencyalert_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyalert',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='datetime_localisation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
