# Generated by Django 5.0.4 on 2024-07-31 16:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_emergencyalert_adresse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalIssue',
            fields=[
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_identified', models.DateField(default=django.utils.timezone.now)),
                ('treatment_details', models.TextField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_issues', to='api.child')),
            ],
        ),
    ]
