# Generated by Django 5.0.4 on 2024-08-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_medicalissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='vous_appelle_til',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
