# Generated by Django 5.0.4 on 2024-08-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_child_vous_appelle_til'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertnotification',
            name='type_notification',
            field=models.CharField(blank=True, choices=[('DEMANDE', 'demande'), ('alerte', 'alerte')], max_length=10, null=True),
        ),
    ]
