# Generated by Django 5.0.4 on 2024-08-07 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_user_fcm_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertnotification',
            name='contact',
        ),
        migrations.AddField(
            model_name='alertnotification',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_parents', to='api.parent'),
        ),
    ]
