# Generated by Django 5.0.4 on 2024-08-07 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alertnotification_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertnotification',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_contact', to='api.emergencycontact'),
        ),
    ]
