# Generated by Django 5.0.4 on 2024-08-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_alertnotification_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
