# Generated by Django 5.0.4 on 2024-09-04 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_emergencycontact_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointTrajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('ordre', models.IntegerField(blank=True, editable=False)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.child')),
            ],
        ),
    ]
