# Generated by Django 5.0.4 on 2024-09-05 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_pointtrajet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointtrajet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pointtrajet',
            name='libelle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pointtrajet',
            name='ordre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PerimetreSecurite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rayon', models.FloatField()),
                ('point_trajet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.pointtrajet')),
            ],
        ),
    ]
