# Generated by Django 5.0.4 on 2024-09-06 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_pointtrajet_is_active_pointtrajet_libelle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointtrajet',
            name='enfant',
        ),
        migrations.AddField(
            model_name='perimetresecurite',
            name='enfant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.child'),
        ),
        migrations.AddField(
            model_name='pointtrajet',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.parent'),
        ),
    ]
