# Generated by Django 5.0.4 on 2024-09-07 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_pointtrajet_enfant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perimetresecurite',
            name='point_trajet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pointtrajet'),
        ),
    ]
