# Generated by Django 5.0.4 on 2024-09-12 21:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_perimetresecurite_point_trajet'),
    ]

    operations = [
        migrations.AddField(
            model_name='perimetresecurite',
            name='slug',
            field=models.SlugField(default=uuid.uuid1),
        ),
        migrations.AddField(
            model_name='pointtrajet',
            name='slug',
            field=models.SlugField(default=uuid.uuid1),
        ),
    ]
