# Generated by Django 5.0.4 on 2024-10-31 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_familymember_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertnotification',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.emergencyalert'),
        ),
    ]
