# Generated by Django 5.0.4 on 2024-10-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_alter_alertnotification_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertnotification',
            name='status',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('refusé', 'Refusé'), ('accepté', 'Accepté')], default='en_cours', max_length=10),
        ),
        migrations.AddField(
            model_name='demande',
            name='status',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('refusé', 'Refusé'), ('accepté', 'Accepté')], default='en_cours', max_length=10),
        ),
    ]
