# Generated by Django 5.0.4 on 2024-11-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_demande_parent_recepteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertnotification',
            name='type_notification',
            field=models.CharField(choices=[('DEMANDE', 'demande'), ('alerte', 'alerte')], default='alerte', max_length=10),
        ),
    ]
