# Generated by Django 5.0.4 on 2024-11-06 13:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_alter_alertnotification_type_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertnotification',
            name='slug',
            field=models.SlugField(default=uuid.uuid1),
        ),
    ]
