# Generated by Django 5.0.4 on 2024-11-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alertnotification_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='perimetresecurite',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
