# Generated by Django 5.0.4 on 2025-02-12 13:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_alertnotification_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perimetresecurite',
            name='enfant',
        ),
        migrations.RemoveField(
            model_name='perimetresecurite',
            name='point_trajet',
        ),
        migrations.AddField(
            model_name='perimetresecurite',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perimetresecurite',
            name='libelle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perimetresecurite',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perimetresecurite',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.parent'),
        ),
        migrations.CreateModel(
            name='ChildWithPerimetreSecurite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.child')),
                ('perimetre_securite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perimetresecurite')),
            ],
        ),
    ]
