# Generated by Django 5.0.4 on 2025-02-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_remove_perimetresecurite_enfant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='battery_level',
            field=models.IntegerField(default=100, help_text='Niveau de batterie en pourcentage (0-100)'),
        ),
    ]
