# Generated by Django 5.0.4 on 2025-05-26 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_child_battery_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='enfant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.child'),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=20, unique=True)),
                ('model_name', models.CharField(max_length=50)),
                ('dev_type', models.CharField(max_length=20)),
                ('child', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device', to='api.child')),
            ],
        ),
        migrations.CreateModel(
            name='BatteryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery', models.IntegerField()),
                ('status', models.CharField(choices=[('1', 'Unknown'), ('2', 'Charging'), ('3', 'Not Charging'), ('4', 'Disconnected'), ('5', 'Fully Charged')], max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battery_statuses', to='api.device')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='api.device'),
        ),
    ]
