# Generated by Django 5.0.4 on 2025-05-30 11:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_alter_location_enfant_device_batterystatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid1)),
                ('serialnumber', models.IntegerField(choices=[(0, 'Bouton 1'), (1, 'Bouton 2'), (2, 'Bouton 3')])),
                ('number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_numbers', to='api.device')),
            ],
            options={
                'unique_together': {('device', 'serialnumber')},
            },
        ),
    ]
