# Generated by Django 5.0.4 on 2025-06-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_alter_familynumber_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='cell_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('gps', 'GPS'), ('wifi', 'Wi-Fi'), ('cell', 'Cell')], default='gps', max_length=10),
        ),
        migrations.AddField(
            model_name='location',
            name='wifi_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
