# Generated by Django 5.0.4 on 2025-06-11 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_location_cell_info_location_location_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyalert',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_device_statuses', to='api.device'),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='location_type',
            field=models.CharField(choices=[('gps', 'GPS'), ('wifi', 'Wi-Fi'), ('cell', 'Cell')], default='gps', max_length=10),
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.child'),
        ),
    ]
