# Generated by Django 5.0.4 on 2025-06-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_emergencyalert_device_emergencyalert_location_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyalert',
            name='cell_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='wifi_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
