# Generated by Django 5.0.4 on 2025-07-28 12:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_batterystatus_created_at_device_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='device',
            name='battery_level',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='device',
            name='date_de_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='ecole',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='device',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='device',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='numeros_urgences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='otp_token',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='device',
            name='registration_method',
            field=models.CharField(blank=True, choices=[('GOOGLE', 'GOOGLE'), ('FACEBOOK', 'FACEBOOK'), ('APPLE', 'APPLE'), ('NORMAL', 'NORMAL')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='slug',
            field=models.SlugField(default=uuid.uuid1),
        ),
        migrations.AddField(
            model_name='device',
            name='type_appareil',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('PARENT', 'PARENT'), ('CHILD', 'CHILD'), ('TUTEUR', 'TUTEUR')], default='device', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='vous_appelle_til',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
