# Generated by Django 5.0.4 on 2025-07-28 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_device_accepted_terms_device_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergy',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allergies_device', to='api.device'),
        ),
        migrations.AddField(
            model_name='medicalissue',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_issues_device', to='api.device'),
        ),
    ]
