# Generated by Django 5.0.4 on 2025-08-07 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_allergy_device_medicalissue_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='childwithperimetresecurite',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perimetre_secure_device', to='api.device'),
        ),
        migrations.AlterField(
            model_name='childwithperimetresecurite',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.child'),
        ),
    ]
