# Generated by Django 5.0.4 on 2025-12-11 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_childwithperimetresecurite_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demande_device', to='api.device'),
        ),
    ]
