# Generated by Django 5.0.4 on 2026-06-12 16:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_user_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
                ('image', models.ImageField(upload_to='device_photos/')),
                ('timestamp', models.CharField(max_length=20)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.device')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
    ]
