# Generated by Django 5.0.4 on 2026-06-15 16:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_devicephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedometerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
                ('steps', models.IntegerField(default=0)),
                ('rolls', models.IntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedometer_data', to='api.device')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
