# Generated by Django 5.0.4 on 2026-06-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_pedometerdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='date_sortie_zone',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='hors_zone',
            field=models.BooleanField(default=False),
        ),
    ]
