# Generated by Django 5.0.4 on 2026-06-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_child_date_sortie_zone_child_hors_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='date_sortie_zone',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='hors_zone',
            field=models.BooleanField(default=False),
        ),
    ]
