# Generated by Django 5.0.4 on 2026-06-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_device_date_sortie_zone_device_hors_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20),
        ),
    ]
