name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        env:
          EC2_HOST: 3.84.229.155             # Remplace par l'adresse IP publique de ton instance EC2
          EC2_USER: ubuntu                   # Utilisateur SSH par défaut pour EC2
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
          ssh $EC2_USER@$EC2_HOST << 'EOF'
            cd ~/kaaraange                  # Navigue vers le répertoire de ton projet
            git pull origin main            # Mets à jour le dépôt Git
            source venv/bin/activate        # Active l'environnement virtuel
            pip install -r requirements.txt # Mets à jour les dépendances
            python manage.py migrate        # Applique les migrations
            python manage.py collectstatic --noinput # Collecte les fichiers statiques
            sudo systemctl restart gunicorn # Redémarre Gunicorn ou le serveur web
          EOF